using Mapster;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SchoolAPI.DTOs.Schedule;
using SchoolAPI.Models.People;
using SchoolAPI.Models.Schedules;
using SchoolAPI.Models.SubjectAndBridge;
using SchoolAPI.Repositories.Schedules;
using SchoolAPI.Repositories.School_Structures;
using SchoolAPI.Repositories.TeacherSubjectClasses;

namespace SchoolAPI.Services.Schedules;

public class ScheduleService : IScheduleService
{
    private readonly IScheduleRepository _scheduleRepo;
    private readonly IClassRepository _classRepo;
    private readonly ITeacherSubjectClassRepository _teacherSubjectClassRepo;
    public ScheduleService(
        IScheduleRepository scheduleRepo,
        IClassRepository classRepo,
        ITeacherSubjectClassRepository teacherSubjectClassRepo)
    {
        _scheduleRepo = scheduleRepo;
        _classRepo = classRepo;
        _teacherSubjectClassRepo = teacherSubjectClassRepo;
    }

    public async Task<ScheduleResponseDto?> GetByIdAsync(string id)
    {
        var schedule = await _scheduleRepo.GetByIdAsync(id);
        return schedule?.Adapt<ScheduleResponseDto>();
    }

    public async Task<IEnumerable<ScheduleResponseDto>> GetAllAsync()
    {
        var schedules = await _scheduleRepo.GetAllAsync();
        return schedules.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    public async Task<IEnumerable<ScheduleResponseDto>> GetByClassIdAsync(string classId)
    {
        var schedules = await _scheduleRepo.GetByClassIdAsync(classId);
        return schedules.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    public async Task<IEnumerable<ScheduleResponseDto>> GetByTeacherIdAsync(string teacherId)
    {
        var schedules = await _scheduleRepo.GetByTeacherIdAsync(teacherId);
        return schedules.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    public async Task<ScheduleResponseDto> CreateAsync(ScheduleRequestCreateDto dto)
    {
        var (start, end) = ValidateAndResolveSlot(dto.Day, dto.StartTime, dto.EndTime);
        ValidateTimeRange(dto.StartTime, dto.EndTime);

        var tsc = await _teacherSubjectClassRepo.GetByIdAsync(dto.TeacherSubjectClassId)
        ?? throw new KeyNotFoundException(
            $"TeacherSubjectClass '{dto.TeacherSubjectClassId}' not found.");

        await EnsureNoClassOverlapAsync(tsc.ClassSubject.ClassId, dto.Day, start, end);
        await EnsureNoTeacherOverlapAsync(tsc.TeacherId, dto.Day, start, end);

        var schedule = new Schedule
        {
            ClassId = tsc.ClassSubject.ClassId,
            SubjectId = tsc.ClassSubject.SubjectId,
            TeacherId = tsc.TeacherId,
            Day = dto.Day,
            StartTime = start,
            EndTime = end,
            IsAutoGenerated = false
        };

        await _scheduleRepo.AddAsync(schedule);

        var created = await _scheduleRepo.GetByIdAsync(schedule.Id);
        return created!.Adapt<ScheduleResponseDto>();
    }

    public async Task<ScheduleResponseDto> UpdateAsync(string id, ScheduleRequestUpdateDto dto)
    {
        var schedule = await _scheduleRepo.GetByIdAsync(id)
            ?? throw new KeyNotFoundException($"Schedule '{id}' not found.");

        var (start, end) = ValidateAndResolveSlot(dto.Day, dto.StartTime, dto.EndTime);

        var tsc = await _teacherSubjectClassRepo.GetByIdAsync(dto.TeacherSubjectClassId)
            ?? throw new KeyNotFoundException(
                $"TeacherSubjectClass '{dto.TeacherSubjectClassId}' not found.");

        // A schedule slot belongs to one class; you can't use Update to move it to a different class.
        if (tsc.ClassSubject.ClassId != schedule.ClassId)
            throw new InvalidOperationException(
                "Cannot reassign a schedule slot to a different class via update.");

        await EnsureNoClassOverlapAsync(
            schedule.ClassId, dto.Day,
            start, end,
            excludeId: id);

        await EnsureNoTeacherOverlapAsync(
            tsc.TeacherId, dto.Day,
            start, end,
            excludeId: id);

        schedule.TeacherId = tsc.TeacherId;
        schedule.SubjectId = tsc.ClassSubject.SubjectId;
        schedule.Day = dto.Day;
        schedule.StartTime = dto.StartTime;
        schedule.EndTime = dto.EndTime;
        schedule.IsAutoGenerated = false; // manual override

        await _scheduleRepo.UpdateAsync(schedule);

        var updated = await _scheduleRepo.GetByIdAsync(id);
        return updated!.Adapt<ScheduleResponseDto>();
    }

    public async Task DeleteAsync(string id)
    {
        var schedule = await _scheduleRepo.GetByIdAsync(id)
            ?? throw new KeyNotFoundException($"Schedule '{id}' not found.");

        await _scheduleRepo.DeleteAsync(schedule);
    }

    public async Task<IEnumerable<ScheduleResponseDto>> AutoGenerateAsync(
    AutoGenerateScheduleRequestDto request)
    {
        var @class = await _classRepo.GetByIdWithSubjectsAndTeachersAsync(request.ClassId)
            ?? throw new KeyNotFoundException($"Class '{request.ClassId}' not found.");

        var teacherSubjects = @class.ClassSubjects
            .SelectMany(cs => cs.TeacherSubjectClasses)
            .ToList();

        if (teacherSubjects.Count < 2 || teacherSubjects.Count > 9)
            throw new InvalidOperationException(
                $"Class must have between 2 and 9 subject-teacher assignments. Found {teacherSubjects.Count}.");

        var days = ScheduleSlots.Days;
        var slotsByDay = days.ToDictionary(
            day => day,
            day => ScheduleSlots.SlotsFor(day)
                .Select(s => (Start: s.Start.ToTimeSpan(), End: s.End.ToTimeSpan()))
                .ToArray());

        const int TargetTeachingPeriods = 31; // TODO: derive from config instead of hardcoding if this varies per class

        var totalWeeklySlots = days.Sum(d => ScheduleSlots.SlotsFor(d).Length);
        if (totalWeeklySlots < TargetTeachingPeriods)
            throw new InvalidOperationException(
                $"Only {totalWeeklySlots} slots exist in the week but {TargetTeachingPeriods} teaching periods are required.");

        // NEW: allocate exact period counts per subject (min-first, then priority fill).
        var subjectNames = teacherSubjects.Select(ts => ts.ClassSubject.Subject.Name).Distinct().ToList();
        var allocation = AllocatePeriods(subjectNames, TargetTeachingPeriods);

        var demand = teacherSubjects
            .Select(ts => (ts, Periods: allocation[ts.ClassSubject.Subject.Name]))
            .ToList();

        var schedules = new List<Schedule>();
        var usedSlots = new HashSet<(SchoolDay, TimeSpan)>();
        var usedTeacherSlots = new HashSet<(string, SchoolDay, TimeSpan)>();
        var usedSubjectDays = new Dictionary<string, HashSet<SchoolDay>>();

        var dayIndex = 0;
        var slotIndex = 0;

        foreach (var (ts, periods) in demand)
        {
            var subjectDays = usedSubjectDays.TryGetValue(ts.ClassSubject.SubjectId, out var set)
                ? set
                : usedSubjectDays[ts.ClassSubject.SubjectId] = new HashSet<SchoolDay>();

            var placed = 0;

            for (var attempt = 0; attempt < days.Length && placed < periods; attempt++)
            {
                var day = days[(dayIndex + attempt) % days.Length];
                if (subjectDays.Contains(day)) continue;

                var slots = slotsByDay[day];

                for (var si = 0; si < slots.Length; si++)
                {
                    var (start, end) = slots[(slotIndex + si) % slots.Length];
                    if (usedSlots.Contains((day, start))) continue;
                    if (usedTeacherSlots.Contains((ts.TeacherId, day, start))) continue;

                    usedSlots.Add((day, start));
                    usedTeacherSlots.Add((ts.TeacherId, day, start));
                    subjectDays.Add(day);

                    schedules.Add(new Schedule
                    {
                        ClassId = request.ClassId,
                        SubjectId = ts.ClassSubject.SubjectId,
                        TeacherId = ts.TeacherId,
                        Day = day,
                        StartTime = start,
                        EndTime = end,
                        IsAutoGenerated = true
                    });

                    placed++;
                    break;
                }
            }

            if (placed < periods)
                throw new InvalidOperationException(
                    $"Could only place {placed}/{periods} periods for teacher '{ts.TeacherId}' " +
                    $"and subject '{ts.ClassSubject.SubjectId}'.");

            dayIndex = (dayIndex + 1) % days.Length;
            slotIndex = (slotIndex + 1) % ScheduleSlots.WeekdaySlots.Length;
        }

        // Remaining unfilled slots (totalWeeklySlots - 31 = 4) stay empty as free periods — by design, not filled.

        await _scheduleRepo.DeleteByClassIdAsync(request.ClassId);
        await _scheduleRepo.AddRangeAsync(schedules);

        var saved = await _scheduleRepo.GetByClassIdAsync(request.ClassId);
        return saved.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    private static void ValidateTimeRange(TimeSpan start, TimeSpan end)
    {
        if (start >= end)
            throw new ArgumentException("StartTime must be before EndTime.");
    }

    private async Task EnsureNoClassOverlapAsync(
        string classId, SchoolDay day,
        TimeSpan start, TimeSpan end,
        string? excludeId = null)
    {
        var hasOverlap = await _scheduleRepo
            .HasClassOverlapAsync(classId, day, start, end, excludeId);

        if (hasOverlap)
            throw new InvalidOperationException(
                $"Class already has a schedule that overlaps on {day} {start:hh\\:mm}–{end:hh\\:mm}.");
    }

    private async Task EnsureNoTeacherOverlapAsync(
        string teacherId, SchoolDay day,
        TimeSpan start, TimeSpan end,
        string? excludeId = null)
    {
        var hasOverlap = await _scheduleRepo
            .HasTeacherOverlapAsync(teacherId, day, start, end, excludeId);

        if (hasOverlap)
            throw new InvalidOperationException(
                $"Teacher already has a schedule that overlaps on {day} {start:hh\\:mm}–{end:hh\\:mm}.");
    }


    private static readonly List<(string Subject, int Min, int Max, int Priority)> SubjectPeriodConfig = new()
    {
        ("Mathematics", 4, 6, 1),
        ("Khmer language", 4, 6, 1),
        ("English", 4, 5, 2),
        ("Physics", 3, 4, 3),
        ("Chemistry", 3, 4, 3),
        ("Biology", 3, 4, 3),
        ("History", 2, 3, 4),
        ("Geography", 2, 3, 4),
        ("Civics and Moral education", 1, 2, 5),
        ("Physical Education", 1, 2, 5),
    };

    private static (string Subject, int Min, int Max, int Priority) GetSubjectConfig(string subjectName) =>
        SubjectPeriodConfig.FirstOrDefault(c =>
            string.Equals(c.Subject, subjectName, StringComparison.OrdinalIgnoreCase))
        is var found && found != default
            ? found
            : (subjectName, 1, 1, 99); // fallback: 1 period, lowest priority

    /// <summary>
    /// Allocates exactly <paramref name="target"/> periods across the given subjects,
    /// starting each at its minimum, then distributing the remainder by priority
    /// (lower Priority number = filled first) until each subject's Max or the target is hit.
    /// </summary>
    private static Dictionary<string, int> AllocatePeriods(
        IEnumerable<string> subjectNames, int target)
    {
        var configs = subjectNames
            .Select(GetSubjectConfig)
            .ToList();

        var allocation = configs.ToDictionary(c => c.Subject, c => c.Min);
        var currentTotal = allocation.Values.Sum();

        if (currentTotal > target)
            throw new InvalidOperationException(
                $"Sum of subject minimums ({currentTotal}) exceeds target periods ({target}).");

        var remaining = target - currentTotal;

        // Highest priority first (lowest number), stable order within same priority.
        var byPriority = configs.OrderBy(c => c.Priority).ToList();

        while (remaining > 0)
        {
            var progressedThisPass = false;

            foreach (var c in byPriority)
            {
                if (remaining == 0) break;
                if (allocation[c.Subject] >= c.Max) continue;

                allocation[c.Subject]++;
                remaining--;
                progressedThisPass = true;
            }

            // No subject had room left but periods remain — target is unreachable given the Max caps.
            if (!progressedThisPass) break;
        }

        if (remaining > 0)
            throw new InvalidOperationException(
                $"Could not allocate {remaining} remaining period(s): all subjects are at Max.");

        return allocation;
    }

    private static (TimeSpan Start, TimeSpan End) ValidateAndResolveSlot(SchoolDay day, TimeSpan start, TimeSpan end)
    {
        var validSlots = ScheduleSlots.SlotsFor(day)
            .Select(s => (Start: s.Start.ToTimeSpan(), End: s.End.ToTimeSpan()))
            .ToArray();

        var match = validSlots.FirstOrDefault(s => s.Start == start && s.End == end);

        if (match == default)
            throw new InvalidOperationException(
                $"'{start:hh\\:mm}-{end:hh\\:mm}' is not a valid period for {day}. " +
                $"Valid periods: {string.Join(", ", validSlots.Select(s => $"{s.Start:hh\\:mm}-{s.End:hh\\:mm}"))}");

        return match;
    }

    public async Task<IEnumerable<ScheduleSlotDtoForManualCreation>> GetDaySlotsAsync(string classId, SchoolDay day)
    {
        // Make sure the class actually exists before doing anything else.
        var classExists = await _classRepo.ExistsAsync(classId);
        if (!classExists)
            throw new KeyNotFoundException($"Class '{classId}' not found.");

        var validSlots = ScheduleSlots.SlotsFor(day)
            .Select(s => (Start: s.Start.ToTimeSpan(), End: s.End.ToTimeSpan()))
            .ToArray();

        if (validSlots.Length == 0)
            throw new InvalidOperationException($"No periods defined for {day}.");

        // Pull this class's full week, then filter down to just this day.
        // (Reuses the existing repo method rather than adding a new narrower query.)
        var existingForDay = (await _scheduleRepo.GetByClassIdAsync(classId))
            .Where(s => s.Day == day)
            .ToDictionary(s => s.StartTime);

        return validSlots.Select(slot =>
        {
            existingForDay.TryGetValue(slot.Start, out var match);
            return new ScheduleSlotDtoForManualCreation(
                slot.Start,
                slot.End,
                IsOccupied: match is not null,
                Schedule: match?.Adapt<ScheduleResponseDto>()
            );
        });
    }
}