using Mapster;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SchoolAPI.DTOs.Schedule;
using SchoolAPI.Models.People;
using SchoolAPI.Models.Schedules;
using SchoolAPI.Models.SubjectAndBridge;
using SchoolAPI.Repositories;
using SchoolAPI.Repositories.Schedules;
using SchoolAPI.Repositories.School_Structures;
using SchoolAPI.Repositories.TeacherSubjectClasses;

namespace SchoolAPI.Services.Schedules;

public class ScheduleService : IScheduleService
{
    private readonly ILogger<ScheduleService> _logger;
    private readonly IScheduleRepository _scheduleRepo;
    private readonly IClassRepository _classRepo;
    private readonly ITeacherSubjectClassRepository _teacherSubjectClassRepo;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IConfiguration _configuration;
    public ScheduleService(
        IScheduleRepository scheduleRepo,
        IClassRepository classRepo,
        ITeacherSubjectClassRepository teacherSubjectClassRepo,
        IUnitOfWork unitOfWork, ILogger<ScheduleService> logger, IConfiguration configuration)
    {
        _scheduleRepo = scheduleRepo;
        _classRepo = classRepo;
        _teacherSubjectClassRepo = teacherSubjectClassRepo;
        _unitOfWork = unitOfWork;
        _logger = logger;
        _configuration = configuration;
    }

    public async Task<ScheduleResponseDto?> GetByIdAsync(string id)
    {
        var schedule = await _scheduleRepo.GetByIdAsync(id);
        return schedule?.Adapt<ScheduleResponseDto>();
    }

    public async Task<IEnumerable<ScheduleResponseDto>> GetAllAsync()
    {
        var schedules = await _scheduleRepo.GetAllAsync();
        return schedules.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    public async Task<IEnumerable<ScheduleResponseDto>> GetByClassIdAsync(string classId)
    {
        var schedules = await _scheduleRepo.GetByClassIdAsync(classId);
        return schedules.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    public async Task<IEnumerable<ScheduleResponseDto>> GetByTeacherIdAsync(string teacherId)
    {
        var schedules = await _scheduleRepo.GetByTeacherIdAsync(teacherId);
        return schedules.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    public async Task<ScheduleResponseDto> CreateAsync(ScheduleRequestCreateDto dto)
    {
        var (start, end) = ValidateAndResolveSlot(dto.Day, dto.StartTime, dto.EndTime);
        ValidateTimeRange(dto.StartTime, dto.EndTime);

        var tsc = await _teacherSubjectClassRepo.GetByIdAsync(dto.TeacherSubjectClassId)
        ?? throw new KeyNotFoundException(
            $"TeacherSubjectClass '{dto.TeacherSubjectClassId}' not found.");

        await EnsureNoClassOverlapAsync(tsc.ClassSubject.ClassId, dto.Day, start, end);
        await EnsureNoTeacherOverlapAsync(tsc.TeacherId, dto.Day, start, end);

        var schedule = new Schedule
        {
            ClassId = tsc.ClassSubject.ClassId,
            SubjectId = tsc.ClassSubject.SubjectId,
            TeacherId = tsc.TeacherId,
            Day = dto.Day,
            StartTime = start,
            EndTime = end,
            IsAutoGenerated = false
        };

        await _scheduleRepo.AddAsync(schedule);

        var created = await _scheduleRepo.GetByIdAsync(schedule.Id);
        return created!.Adapt<ScheduleResponseDto>();
    }

    public async Task<ScheduleResponseDto> UpdateAsync(string id, ScheduleRequestUpdateDto dto)
    {
        var schedule = await _scheduleRepo.GetByIdAsync(id)
            ?? throw new KeyNotFoundException($"Schedule '{id}' not found.");

        var (start, end) = ValidateAndResolveSlot(dto.Day, dto.StartTime, dto.EndTime);

        var tsc = await _teacherSubjectClassRepo.GetByIdAsync(dto.TeacherSubjectClassId)
            ?? throw new KeyNotFoundException(
                $"TeacherSubjectClass '{dto.TeacherSubjectClassId}' not found.");

        // A schedule slot belongs to one class; you can't use Update to move it to a different class.
        if (tsc.ClassSubject.ClassId != schedule.ClassId)
            throw new InvalidOperationException(
                "Cannot reassign a schedule slot to a different class via update.");

        await EnsureNoClassOverlapAsync(
            schedule.ClassId, dto.Day,
            start, end,
            excludeId: id);

        await EnsureNoTeacherOverlapAsync(
            tsc.TeacherId, dto.Day,
            start, end,
            excludeId: id);

        schedule.TeacherId = tsc.TeacherId;
        schedule.SubjectId = tsc.ClassSubject.SubjectId;
        schedule.Day = dto.Day;
        schedule.StartTime = dto.StartTime;
        schedule.EndTime = dto.EndTime;
        schedule.IsAutoGenerated = false; // manual override
        schedule.UpdatedAt = DateTime.UtcNow;

        await _scheduleRepo.UpdateAsync(schedule);

        var updated = await _scheduleRepo.GetByIdAsync(id);
        return updated!.Adapt<ScheduleResponseDto>();
    }

    public async Task<bool> DeleteAsync(string id)
    {
        var schedule = await _scheduleRepo.GetByIdAsync(id)
            ?? throw new KeyNotFoundException($"Schedule '{id}' not found.");

        await _scheduleRepo.DeleteAsync(schedule);
        return true;
    }

    public async Task<IEnumerable<ScheduleResponseDto>> AutoGenerateAsync(
        AutoGenerateScheduleRequestDto request)
    {
        var @class = await _classRepo.GetByIdWithSubjectsAndTeachersAsync(request.ClassId)
            ?? throw new KeyNotFoundException($"Class '{request.ClassId}' not found.");

        var teacherSubjects = @class.ClassSubjects
            .SelectMany(cs => cs.TeacherSubjectClasses)
            .ToList();

        if (teacherSubjects.Count < 2 || teacherSubjects.Count > 10)
            throw new InvalidOperationException(
                $"Class must have between 2 and 10 subject-teacher assignments. Found {teacherSubjects.Count}.");

        var days = ScheduleSlots.Days;
        var slotsByDay = days.ToDictionary(
            day => day,
            day => ScheduleSlots.SlotsFor(day)
                .Select(s => (Start: s.Start.ToTimeSpan(), End: s.End.ToTimeSpan()))
                .ToArray());

        var TargetTeachingPeriods = _configuration.GetValue<int>("Scheduler:TargetTeachingPeriods", 35);

        var totalWeeklySlots = days.Sum(d => ScheduleSlots.SlotsFor(d).Length);
        if (totalWeeklySlots < TargetTeachingPeriods)
            throw new InvalidOperationException(
                $"Only {totalWeeklySlots} slots exist in the week but {TargetTeachingPeriods} teaching periods are required.");

        // Allocate exact period counts per SUBJECT (not per teacher-subject row), keyed by SubjectId.
        var subjectGroups = teacherSubjects
            .GroupBy(ts => ts.ClassSubject.SubjectId)
            .Select(g => new
            {
                SubjectId = g.Key,
                SubjectName = g.First().ClassSubject.Subject.Name,
                TeacherAssignments = g.ToList()
            })
            .ToList();

        foreach (var g in subjectGroups)
        {
            var cfg = GetSubjectConfig(g.SubjectName);
            Console.WriteLine($"{g.SubjectName}  Min={cfg.Min}  Max={cfg.Max}");
        }

        var minSum = subjectGroups.Sum(g => GetSubjectConfig(g.SubjectName).Min);
        var maxSum = subjectGroups.Sum(g => GetSubjectConfig(g.SubjectName).Max);

        if (TargetTeachingPeriods < minSum || TargetTeachingPeriods > maxSum)
            throw new InvalidOperationException(
                $"Target of {TargetTeachingPeriods} periods is not achievable with this class's subjects " +
                $"(min possible: {minSum}, max possible: {maxSum}).");

        var teacherIds = teacherSubjects.Select(ts => ts.TeacherId).Distinct().ToList();
        var teacherBusySlots = await _scheduleRepo.GetTeacherBusySlotsAsync(teacherIds);

        var usedTeacherSlots = teacherBusySlots
            .Where(s => s.ClassId != request.ClassId)
            .Select(s => (s.TeacherId, s.Day, s.StartTime))
            .ToHashSet();

        var totalWeeklySlotSet = days
        .SelectMany(d => slotsByDay[d].Select(s => (Day: d, s.Start)))
        .ToHashSet();

        foreach (var ts in teacherSubjects)
        {
            var busyForTeacher = usedTeacherSlots
                .Where(u => u.TeacherId == ts.TeacherId)
                .Select(u => (u.Day, u.StartTime))
                .ToHashSet();

            var available = totalWeeklySlotSet.Count(slot => !busyForTeacher.Contains((slot.Day, slot.Start)));
            var minRequired = GetSubjectConfig(ts.ClassSubject.Subject.Name).Min;

            if (available < minRequired)
                throw new InvalidOperationException(
                    $"Teacher '{ts.TeacherId}' has only {available} free slot(s) this week " +
                    $"but needs at least {minRequired} for '{ts.ClassSubject.Subject.Name}'. " +
                    $"Check their existing schedule across other classes.");
        }

        var allocation = AllocatePeriods(
            subjectGroups.Select(g => (g.SubjectId, g.SubjectName)),
            TargetTeachingPeriods);

        var demand = subjectGroups
        .SelectMany(g =>
        {
            var total = allocation[g.SubjectId];
            var teacherCount = g.TeacherAssignments.Count;
            var basePerTeacher = total / teacherCount;
            var remainder = total % teacherCount;

            return g.TeacherAssignments.Select((ts, i) => (
                ts,
                SubjectId: g.SubjectId,
                Periods: basePerTeacher + (i < remainder ? 1 : 0)
            ));
        })
        .Where(d => d.Periods > 0)
        .ToList();

        const int MaxPeriodsPerSubjectPerDay = 2;
        const int MaxFreePeriodsPerDay = 2;

        var schedules = new List<Schedule>();
        var usedSlots = new HashSet<(SchoolDay, TimeSpan)>();
        // Now tracks a COUNT per subject per day, so up to MaxPeriodsPerSubjectPerDay can land on the same day.
        var subjectDayCounts = new Dictionary<(string SubjectId, SchoolDay Day), int>();
        var filledPerDay = days.ToDictionary(d => d, d => 0);

        var dayIndex = 0;
        var slotIndex = 0;

        foreach (var (ts, subjectId, periods) in demand)
        {

            var placed = 0;

            var candidateDays = days
               .Select((day, i) => (day, offset: (i - dayIndex + days.Length) % days.Length))
               .OrderByDescending(x => slotsByDay[x.day].Length - filledPerDay[x.day]) // most free slots first
               .ThenBy(x => x.offset) // stable tie-break, preserves round-robin-ish spread
               .Select(x => x.day)
               .ToList();

            foreach (var day in candidateDays)
            {
                if (placed >= periods) break;

                var dayKey = (subjectId, day);
                var countToday = subjectDayCounts.GetValueOrDefault(dayKey);
                if (countToday >= MaxPeriodsPerSubjectPerDay) continue;

                var slots = slotsByDay[day];

                for (var si = 0; si < slots.Length && placed < periods && countToday < MaxPeriodsPerSubjectPerDay; si++)
                {
                    var (start, end) = slots[(slotIndex + si) % slots.Length];
                    if (usedSlots.Contains((day, start))) continue;
                    if (usedTeacherSlots.Contains((ts.TeacherId, day, start))) continue;

                    usedSlots.Add((day, start));
                    usedTeacherSlots.Add((ts.TeacherId, day, start));
                    subjectDayCounts[dayKey] = ++countToday;

                    filledPerDay[day]++; // NEW

                    schedules.Add(new Schedule
                    {
                        ClassId = request.ClassId,
                        SubjectId = subjectId,
                        TeacherId = ts.TeacherId,
                        Day = day,
                        StartTime = start,
                        EndTime = end,
                        IsAutoGenerated = true
                    });

                    placed++;
                }
            }

            if (placed < periods)
                throw new InvalidOperationException(
                    $"Could only place {placed}/{periods} periods for teacher '{ts.TeacherId}' " +
                    $"and subject '{ts.ClassSubject.SubjectId}'.");

            dayIndex = (dayIndex + 1) % days.Length;
            slotIndex = (slotIndex + 1) % ScheduleSlots.WeekdaySlots.Length;
        }

        // FIX: best-effort rebalance instead of a hard throw — moves periods from
        // over-full days to days with room, respecting subject/teacher/class conflicts.
        // Cross-class teacher commitments (usedTeacherSlots) are honored during moves too.
        RebalanceFreePeriods(
            schedules, slotsByDay, days, filledPerDay, subjectDayCounts,
            usedTeacherSlots, MaxPeriodsPerSubjectPerDay, MaxFreePeriodsPerDay);

        var stillViolating = days
           .Select(d => (Day: d, Free: slotsByDay[d].Length - filledPerDay[d]))
           .Where(x => x.Free > MaxFreePeriodsPerDay)
           .ToList();

        // Don't throw — log and proceed. A schedule that's slightly imperfect on free-period
        // spread is far better than failing the entire class's generation.
        if (stillViolating.Count > 0)
        {
            _logger.LogWarning(
                "Class '{ClassId}' schedule could not fully satisfy the free-period cap on: {Days}",
                request.ClassId,
                string.Join(", ", stillViolating.Select(x => $"{x.Day} ({x.Free} free, max {MaxFreePeriodsPerDay})")));
        }

        // Remaining unfilled slots (totalWeeklySlots - 31 = 4) stay empty as free periods — by design, not filled.

        //use transaction to ensure atomicity
        await _unitOfWork.ExecuteInTransactionAsync(async () =>
        {
            await _scheduleRepo.DeleteByClassIdAsync(request.ClassId);
            await _scheduleRepo.AddRangeAsync(schedules);
        });

        var saved = await _scheduleRepo.GetByClassIdAsync(request.ClassId);
        return saved.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    private static void ValidateTimeRange(TimeSpan start, TimeSpan end)
    {
        if (start >= end)
            throw new ArgumentException("StartTime must be before EndTime.");
    }

    private async Task EnsureNoClassOverlapAsync(
        string classId, SchoolDay day,
        TimeSpan start, TimeSpan end,
        string? excludeId = null)
    {
        var hasOverlap = await _scheduleRepo
            .HasClassOverlapAsync(classId, day, start, end, excludeId);

        if (hasOverlap)
            throw new InvalidOperationException(
                $"Class already has a schedule that overlaps on {day} {start:hh\\:mm}–{end:hh\\:mm}.");
    }

    private async Task EnsureNoTeacherOverlapAsync(
        string teacherId, SchoolDay day,
        TimeSpan start, TimeSpan end,
        string? excludeId = null)
    {
        var hasOverlap = await _scheduleRepo
            .HasTeacherOverlapAsync(teacherId, day, start, end, excludeId);

        if (hasOverlap)
            throw new InvalidOperationException(
                $"Teacher already has a schedule that overlaps on {day} {start:hh\\:mm}–{end:hh\\:mm}.");
    }


    private static readonly List<(string Subject, int Min, int Max, int Priority)> SubjectPeriodConfig = new()
    {
        ("Mathematics", 4, 6, 1),
        ("Khmer language", 4, 6, 1),
        ("English", 4, 5, 2),
        ("Physics", 3, 4, 3),
        ("Chemistry", 3, 4, 3),
        ("Biology", 3, 4, 3),
        ("History", 2, 3, 4),
        ("Geography", 2, 3, 4),
        ("Civics and Moral education", 1, 2, 5),
        ("Physical Education", 1, 2, 5),
    };

    private static (string Subject, int Min, int Max, int Priority) GetSubjectConfig(string subjectName) =>
        SubjectPeriodConfig.FirstOrDefault(c =>
            string.Equals(c.Subject, subjectName, StringComparison.OrdinalIgnoreCase))
        is var found && found != default
            ? found
            : (subjectName, 1, 1, 99); // fallback: 1 period, lowest priority

    private static Dictionary<string, int> AllocatePeriods(
        IEnumerable<(string SubjectId, string SubjectName)> subjects, int target)
    {
        var configs = subjects
            .Select(s => (s.SubjectId, s.SubjectName, Config: GetSubjectConfig(s.SubjectName)))
            .ToList();

        var allocation = configs.ToDictionary(c => c.SubjectId, c => c.Config.Min);
        var currentTotal = allocation.Values.Sum();

        if (currentTotal > target)
            throw new InvalidOperationException(
                $"Sum of subject minimums ({currentTotal}) exceeds target periods ({target}).");

        var remaining = target - currentTotal;

        // Highest priority first (lowest number), stable order within same priority.
        var byPriority = configs.OrderBy(c => c.Config.Priority).ToList();

        while (remaining > 0)
        {
            var progressedThisPass = false;

            foreach (var c in byPriority)
            {
                if (remaining == 0) break;
                if (allocation[c.SubjectId] >= c.Config.Max) continue;

                allocation[c.SubjectId]++;
                remaining--;
                progressedThisPass = true;
            }

            // No subject had room left but periods remain — target is unreachable given the Max caps.
            if (!progressedThisPass) break;
        }

        if (remaining > 0)
            throw new InvalidOperationException(
                $"Could not allocate {remaining} remaining period(s): all subjects are at Max.");

        return allocation;
    }

    private static (TimeSpan Start, TimeSpan End) ValidateAndResolveSlot(SchoolDay day, TimeSpan start, TimeSpan end)
    {
        var validSlots = ScheduleSlots.SlotsFor(day)
            .Select(s => (Start: s.Start.ToTimeSpan(), End: s.End.ToTimeSpan()))
            .ToArray();

        var match = validSlots.FirstOrDefault(s => s.Start == start && s.End == end);

        if (match == default)
            throw new InvalidOperationException(
                $"'{start:hh\\:mm}-{end:hh\\:mm}' is not a valid period for {day}. " +
                $"Valid periods: {string.Join(", ", validSlots.Select(s => $"{s.Start:hh\\:mm}-{s.End:hh\\:mm}"))}");

        return match;
    }

    public async Task<IEnumerable<ScheduleSlotDtoForManualCreation>> GetDaySlotsAsync(string classId, SchoolDay day)
    {
        // Make sure the class actually exists before doing anything else.
        var classExists = await _classRepo.ExistsAsync(classId);
        if (!classExists)
            throw new KeyNotFoundException($"Class '{classId}' not found.");

        var validSlots = ScheduleSlots.SlotsFor(day)
            .Select(s => (Start: s.Start.ToTimeSpan(), End: s.End.ToTimeSpan()))
            .ToArray();

        if (validSlots.Length == 0)
            throw new InvalidOperationException($"No periods defined for {day}.");

        // Pull this class's full week, then filter down to just this day.
        // (Reuses the existing repo method rather than adding a new narrower query.)
        var existingForDay = (await _scheduleRepo.GetByClassIdAsync(classId))
            .Where(s => s.Day == day)
            .ToDictionary(s => s.StartTime);

        return validSlots.Select(slot =>
        {
            existingForDay.TryGetValue(slot.Start, out var match);
            return new ScheduleSlotDtoForManualCreation(
                slot.Start,
                slot.End,
                IsOccupied: match is not null,
                Schedule: match?.Adapt<ScheduleResponseDto>()
            );
        });
    }

    private static void RebalanceFreePeriods(
    List<Schedule> schedules,
    Dictionary<SchoolDay, (TimeSpan Start, TimeSpan End)[]> slotsByDay,
    SchoolDay[] days,
    Dictionary<SchoolDay, int> filledPerDay,
    Dictionary<(string SubjectId, SchoolDay Day), int> subjectDayCounts,
    HashSet<(string TeacherId, SchoolDay Day, TimeSpan StartTime)> usedTeacherSlots,
    int maxPeriodsPerSubjectPerDay,
    int maxFreePeriodsPerDay)
    {
        bool MovedSomething()
        {
            var overfull = days
                .Select(d => (Day: d, Free: slotsByDay[d].Length - filledPerDay[d]))
                .Where(x => x.Free > maxFreePeriodsPerDay)
                .OrderByDescending(x => x.Free)
                .ToList();

            if (overfull.Count == 0) return false;

            foreach (var (fromDay, _) in overfull)
            {
                var movable = schedules.Where(s => s.Day == fromDay).ToList();

                var targetDays = days
                    .Where(d => d != fromDay)
                    .Select(d => (Day: d, Free: slotsByDay[d].Length - filledPerDay[d]))
                    .Where(x => x.Free > 0)
                    .OrderByDescending(x => x.Free)
                    .ToList();

                foreach (var sched in movable)
                {
                    foreach (var (toDay, _) in targetDays)
                    {
                        var subjectKey = (sched.SubjectId, toDay);
                        var subjectCountOnTarget = subjectDayCounts.GetValueOrDefault(subjectKey);
                        if (subjectCountOnTarget >= maxPeriodsPerSubjectPerDay) continue;

                        // Cross-class commitment check on the target slot for this teacher.
                        if (usedTeacherSlots.Contains((sched.TeacherId, toDay, default)) &&
                            usedTeacherSlots.Any(u => u.TeacherId == sched.TeacherId && u.Day == toDay))
                        {
                            // handled per-slot below; this outer check is just a cheap skip hint
                        }

                        var toSlots = slotsByDay[toDay];
                        var takenSlots = schedules.Where(s => s.Day == toDay)
                            .Select(s => s.StartTime).ToHashSet();
                        var teacherBusyOnTarget = schedules.Where(s => s.Day == toDay && s.TeacherId == sched.TeacherId)
                            .Select(s => s.StartTime)
                            .Concat(usedTeacherSlots
                                .Where(u => u.TeacherId == sched.TeacherId && u.Day == toDay)
                                .Select(u => u.StartTime))
                            .ToHashSet();

                        var freeSlot = toSlots.FirstOrDefault(s =>
                            !takenSlots.Contains(s.Start) && !teacherBusyOnTarget.Contains(s.Start));

                        if (freeSlot == default) continue;

                        // Perform the move — update all tracking structures to stay consistent.
                        usedTeacherSlots.Remove((sched.TeacherId, sched.Day, sched.StartTime));
                        usedTeacherSlots.Add((sched.TeacherId, toDay, freeSlot.Start));

                        subjectDayCounts[(sched.SubjectId, sched.Day)]--;
                        subjectDayCounts[subjectKey] = subjectCountOnTarget + 1;

                        filledPerDay[fromDay]--;
                        filledPerDay[toDay]++;

                        sched.Day = toDay;
                        sched.StartTime = freeSlot.Start;
                        sched.EndTime = freeSlot.End;

                        return true;
                    }
                }
            }

            return false;
        }

        const int MaxRebalancePasses = 200; // safety valve against pathological inputs
        var passes = 0;
        while (passes++ < MaxRebalancePasses && MovedSomething()) { }
    }
}