using Mapster;
using SchoolAPI.DTOs.Schedule;
using SchoolAPI.Models.Schedules;
using SchoolAPI.Repositories.Schedules;
using SchoolAPI.Repositories.School_Structures;

namespace SchoolAPI.Services.Schedules;

public class ScheduleService : IScheduleService
{
    private readonly IScheduleRepository _scheduleRepo;
    private readonly IClassRepository _classRepo;
    public ScheduleService(
        IScheduleRepository scheduleRepo,
        IClassRepository classRepo)
    {
        _scheduleRepo = scheduleRepo;
        _classRepo = classRepo;
    }

    public async Task<ScheduleResponseDto?> GetByIdAsync(string id)
    {
        var schedule = await _scheduleRepo.GetByIdAsync(id);
        return schedule?.Adapt<ScheduleResponseDto>();
    }

    public async Task<IEnumerable<ScheduleResponseDto>> GetAllAsync()
    {
        var schedules = await _scheduleRepo.GetAllAsync();
        return schedules.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    public async Task<IEnumerable<ScheduleResponseDto>> GetByClassIdAsync(string classId)
    {
        var schedules = await _scheduleRepo.GetByClassIdAsync(classId);
        return schedules.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    public async Task<IEnumerable<ScheduleResponseDto>> GetByTeacherIdAsync(string teacherId)
    {
        var schedules = await _scheduleRepo.GetByTeacherIdAsync(teacherId);
        return schedules.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    public async Task<ScheduleResponseDto> CreateAsync(ScheduleRequestCreateDto dto)
    {
        ValidateTimeRange(dto.StartTime, dto.EndTime);

        await EnsureNoClassOverlapAsync(
            dto.ClassId, dto.Day,
            dto.StartTime, dto.EndTime);

        await EnsureNoTeacherOverlapAsync(
            dto.TeacherId, dto.Day,
            dto.StartTime, dto.EndTime);

        var schedule = dto.Adapt<Schedule>();
        schedule.IsAutoGenerated = false;

        await _scheduleRepo.AddAsync(schedule);

        // Reload with navigation properties for response
        var created = await _scheduleRepo.GetByIdAsync(schedule.Id);
        return created!.Adapt<ScheduleResponseDto>();
    }

    public async Task<ScheduleResponseDto> UpdateAsync(string id, ScheduleRequestUpdateDto dto)
    {
        var schedule = await _scheduleRepo.GetByIdAsync(id)
            ?? throw new KeyNotFoundException($"Schedule '{id}' not found.");

        ValidateTimeRange(dto.StartTime, dto.EndTime);

        await EnsureNoClassOverlapAsync(
            schedule.ClassId, dto.Day,
            dto.StartTime, dto.EndTime,
            excludeId: id);

        await EnsureNoTeacherOverlapAsync(
            dto.TeacherId, dto.Day,
            dto.StartTime, dto.EndTime,
            excludeId: id);

        schedule.TeacherId = dto.TeacherId;
        schedule.Day = dto.Day;
        schedule.StartTime = dto.StartTime;
        schedule.EndTime = dto.EndTime;
        schedule.IsAutoGenerated = false; // manual override

        await _scheduleRepo.UpdateAsync(schedule);

        var updated = await _scheduleRepo.GetByIdAsync(id);
        return updated!.Adapt<ScheduleResponseDto>();
    }

    public async Task DeleteAsync(string id)
    {
        var schedule = await _scheduleRepo.GetByIdAsync(id)
            ?? throw new KeyNotFoundException($"Schedule '{id}' not found.");

        await _scheduleRepo.DeleteAsync(schedule);
    }

    public async Task<IEnumerable<ScheduleResponseDto>> AutoGenerateAsync(
        AutoGenerateScheduleRequestDto request)
    {
        var @class = await _classRepo.GetByIdWithSubjectsAndTeachersAsync(request.ClassId)
            ?? throw new KeyNotFoundException($"Class '{request.ClassId}' not found.");

        var teacherSubjects = @class.ClassSubjects
            .SelectMany(cs => cs.TeacherSubjectClasses)
            .ToList();

        if (teacherSubjects.Count < 2 || teacherSubjects.Count > 6)
            throw new InvalidOperationException(
                $"Class must have between 2 and 6 subject-teacher assignments. Found {teacherSubjects.Count}.");

        var days = Enum.GetValues<SchoolDay>().ToList(); // Mon–Fri
        var slots = BuildTimeSlots(request.DayStartTime, request.DayEndTime,
                                   request.PeriodDurationMinutes, request.BreakDurationMinutes);

        if (slots.Count < teacherSubjects.Count)
            throw new InvalidOperationException(
                "Not enough time slots in the day to fit all subjects.");

        // Delete existing auto-generated schedules for this class
        await _scheduleRepo.DeleteByClassIdAsync(request.ClassId);

        var schedules = new List<Schedule>();
        var slotIndex = 0;

        // Distribute subjects across the week evenly
        foreach (var ts in teacherSubjects)
        {
            var day = days[slotIndex % days.Count];
            var slot = slots[slotIndex % slots.Count];

            // Skip slot if teacher already busy (fallback: find next free slot)
            var (start, end) = slot;
            (day, start, end) = await FindFreeSlot(
                ts.TeacherId, days, slots, slotIndex);

            schedules.Add(new Schedule
            {
                ClassId = request.ClassId,
                SubjectId = ts.ClassSubjectId,
                TeacherId = ts.TeacherId,
                Day = day,
                StartTime = start,
                EndTime = end,
                IsAutoGenerated = true
            });

            slotIndex++;
        }

        await _scheduleRepo.AddRangeAsync(schedules);

        // Reload with navigation properties
        var saved = await _scheduleRepo.GetByClassIdAsync(request.ClassId);
        return saved.Adapt<IEnumerable<ScheduleResponseDto>>();
    }

    private static void ValidateTimeRange(TimeSpan start, TimeSpan end)
    {
        if (start >= end)
            throw new ArgumentException("StartTime must be before EndTime.");
    }

    private async Task EnsureNoClassOverlapAsync(
        string classId, SchoolDay day,
        TimeSpan start, TimeSpan end,
        string? excludeId = null)
    {
        var hasOverlap = await _scheduleRepo
            .HasClassOverlapAsync(classId, day, start, end, excludeId);

        if (hasOverlap)
            throw new InvalidOperationException(
                $"Class already has a schedule that overlaps on {day} {start:hh\\:mm}–{end:hh\\:mm}.");
    }

    private async Task EnsureNoTeacherOverlapAsync(
        string teacherId, SchoolDay day,
        TimeSpan start, TimeSpan end,
        string? excludeId = null)
    {
        var hasOverlap = await _scheduleRepo
            .HasTeacherOverlapAsync(teacherId, day, start, end, excludeId);

        if (hasOverlap)
            throw new InvalidOperationException(
                $"Teacher already has a schedule that overlaps on {day} {start:hh\\:mm}–{end:hh\\:mm}.");
    }

    private static List<(TimeSpan Start, TimeSpan End)> BuildTimeSlots(
        TimeSpan dayStart, TimeSpan dayEnd,
        int periodMinutes, int breakMinutes)
    {
        var slots = new List<(TimeSpan, TimeSpan)>();
        var current = dayStart;

        while (current.Add(TimeSpan.FromMinutes(periodMinutes)) <= dayEnd)
        {
            var end = current.Add(TimeSpan.FromMinutes(periodMinutes));
            slots.Add((current, end));
            current = end.Add(TimeSpan.FromMinutes(breakMinutes));
        }

        return slots;
    }

    private async Task<(SchoolDay Day, TimeSpan Start, TimeSpan End)> FindFreeSlot(
        string teacherId,
        List<SchoolDay> days,
        List<(TimeSpan Start, TimeSpan End)> slots,
        int startIndex)
    {
        for (var i = 0; i < days.Count * slots.Count; i++)
        {
            var idx = (startIndex + i);
            var day = days[idx % days.Count];
            var slot = slots[idx % slots.Count];

            var busy = await _scheduleRepo
                .HasTeacherOverlapAsync(teacherId, day, slot.Start, slot.End);

            if (!busy) return (day, slot.Start, slot.End);
        }

        throw new InvalidOperationException(
            $"No free time slot found for teacher '{teacherId}' across the whole week.");
    }
}