using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SchoolAPI.Migrations
{
    /// <inheritdoc />
    public partial class UpdatedTeacherClassSubject : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_TeacherSubjectClasses_Classes_ClassId",
                table: "TeacherSubjectClasses");

            migrationBuilder.DropForeignKey(
                name: "FK_TeacherSubjectClasses_Subjects_SubjectId",
                table: "TeacherSubjectClasses");

            migrationBuilder.DropIndex(
                name: "IX_Schedules_ClassId",
                table: "Schedules");

            migrationBuilder.DropIndex(
                name: "IX_Schedules_TeacherId",
                table: "Schedules");

            migrationBuilder.DropIndex(
                name: "IX_ClassSubjects_ClassId",
                table: "ClassSubjects");

            migrationBuilder.AlterColumn<string>(
                name: "SubjectId",
                table: "TeacherSubjectClasses",
                type: "varchar(50)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(50)");

            migrationBuilder.AlterColumn<string>(
                name: "ClassId",
                table: "TeacherSubjectClasses",
                type: "varchar(50)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(50)");

            migrationBuilder.AddColumn<string>(
                name: "ClassSubjectId",
                table: "TeacherSubjectClasses",
                type: "varchar(50)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AlterColumn<string>(
                name: "Gender",
                table: "Teachers",
                type: "nvarchar(10)",
                maxLength: 10,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(10)",
                oldNullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "CreatedAt",
                table: "Schedules",
                type: "datetime2",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Schedules",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "UpdatedAt",
                table: "Schedules",
                type: "datetime2",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_TeacherSubjectClasses_ClassSubjectId_TeacherId",
                table: "TeacherSubjectClasses",
                columns: new[] { "ClassSubjectId", "TeacherId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Schedules_ClassId_Day_StartTime",
                table: "Schedules",
                columns: new[] { "ClassId", "Day", "StartTime" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Schedules_TeacherId_Day_StartTime",
                table: "Schedules",
                columns: new[] { "TeacherId", "Day", "StartTime" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ClassSubjects_ClassId_SubjectId",
                table: "ClassSubjects",
                columns: new[] { "ClassId", "SubjectId" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_TeacherSubjectClasses_ClassSubjects_ClassSubjectId",
                table: "TeacherSubjectClasses",
                column: "ClassSubjectId",
                principalTable: "ClassSubjects",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_TeacherSubjectClasses_Classes_ClassId",
                table: "TeacherSubjectClasses",
                column: "ClassId",
                principalTable: "Classes",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_TeacherSubjectClasses_Subjects_SubjectId",
                table: "TeacherSubjectClasses",
                column: "SubjectId",
                principalTable: "Subjects",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_TeacherSubjectClasses_ClassSubjects_ClassSubjectId",
                table: "TeacherSubjectClasses");

            migrationBuilder.DropForeignKey(
                name: "FK_TeacherSubjectClasses_Classes_ClassId",
                table: "TeacherSubjectClasses");

            migrationBuilder.DropForeignKey(
                name: "FK_TeacherSubjectClasses_Subjects_SubjectId",
                table: "TeacherSubjectClasses");

            migrationBuilder.DropIndex(
                name: "IX_TeacherSubjectClasses_ClassSubjectId_TeacherId",
                table: "TeacherSubjectClasses");

            migrationBuilder.DropIndex(
                name: "IX_Schedules_ClassId_Day_StartTime",
                table: "Schedules");

            migrationBuilder.DropIndex(
                name: "IX_Schedules_TeacherId_Day_StartTime",
                table: "Schedules");

            migrationBuilder.DropIndex(
                name: "IX_ClassSubjects_ClassId_SubjectId",
                table: "ClassSubjects");

            migrationBuilder.DropColumn(
                name: "ClassSubjectId",
                table: "TeacherSubjectClasses");

            migrationBuilder.DropColumn(
                name: "CreatedAt",
                table: "Schedules");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Schedules");

            migrationBuilder.DropColumn(
                name: "UpdatedAt",
                table: "Schedules");

            migrationBuilder.AlterColumn<string>(
                name: "SubjectId",
                table: "TeacherSubjectClasses",
                type: "varchar(50)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "varchar(50)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "ClassId",
                table: "TeacherSubjectClasses",
                type: "varchar(50)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "varchar(50)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Gender",
                table: "Teachers",
                type: "varchar(10)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(10)",
                oldMaxLength: 10,
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Schedules_ClassId",
                table: "Schedules",
                column: "ClassId");

            migrationBuilder.CreateIndex(
                name: "IX_Schedules_TeacherId",
                table: "Schedules",
                column: "TeacherId");

            migrationBuilder.CreateIndex(
                name: "IX_ClassSubjects_ClassId",
                table: "ClassSubjects",
                column: "ClassId");

            migrationBuilder.AddForeignKey(
                name: "FK_TeacherSubjectClasses_Classes_ClassId",
                table: "TeacherSubjectClasses",
                column: "ClassId",
                principalTable: "Classes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_TeacherSubjectClasses_Subjects_SubjectId",
                table: "TeacherSubjectClasses",
                column: "SubjectId",
                principalTable: "Subjects",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
