// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolAPI.Data;

#nullable disable

namespace SchoolAPI.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("SchoolAPI.Models.Curriculum_Bridges.ClassSubject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassSubjects", (string)null);
                });

            modelBuilder.Entity("SchoolAPI.Models.Curriculum_Bridges.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] <> ''");

                    b.ToTable("Subjects", null, t =>
                        {
                            t.HasCheckConstraint("CHK_SUBJECT_CODE_NOT_EMPTY", "LEN(LTRIM(RTRIM([Code]))) > 0");

                            t.HasCheckConstraint("CHK_SUBJECT_NAME_NOT_EMPTY", "LEN(LTRIM(RTRIM([Name]))) > 0");
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.Curriculum_Bridges.TeacherSubjectClass", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSubjectClasses", (string)null);
                });

            modelBuilder.Entity("SchoolAPI.Models.Enrollment.Enrollment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DropReason")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DroppedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("SchoolAPI.Models.PaymentsWaitlists.Payment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SlipURL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("StudentId");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CHK_AMOUNT_POSITIVE", "[Amount] > 0");

                            t.HasCheckConstraint("CHK_METHOD_NOT_EMPTY", "LEN(LTRIM(RTRIM([Method]))) > 0");

                            t.HasCheckConstraint("CHK_TYPE_NOT_EMPTY", "LEN(LTRIM(RTRIM([Type]))) > 0");
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.PaymentsWaitlists.Waitlist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("Waitlists", (string)null);
                });

            modelBuilder.Entity("SchoolAPI.Models.People.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SchoolAPI.Models.People.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BackgroundStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LevelId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("code <> ''");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students", null, t =>
                        {
                            t.HasCheckConstraint("CHK_ADDRESS_NOT_EMPTY", "LEN(LTRIM(RTRIM([Address]))) > 0");

                            t.HasCheckConstraint("CHK_BACKGROUNDSTUDY_NOT_EMPTY", "LEN(LTRIM(RTRIM([BackgroundStudy]))) > 0");

                            t.HasCheckConstraint("CHK_CONTACT_NOT_EMPTY", "LEN(LTRIM(RTRIM([Contact]))) > 0");

                            t.HasCheckConstraint("CHK_FATHERNAME_NOT_EMPTY", "LEN(LTRIM(RTRIM([FatherName]))) > 0");

                            t.HasCheckConstraint("CHK_FULLNAME_NOT_EMPTY", "LEN(LTRIM(RTRIM([FullName]))) > 0");

                            t.HasCheckConstraint("CHK_LATINNAME_NOT_EMPTY", "LEN(LTRIM(RTRIM([LatinName]))) > 0");

                            t.HasCheckConstraint("CHK_MOTHERNAME_NOT_EMPTY", "LEN(LTRIM(RTRIM([MotherName]))) > 0");

                            t.HasCheckConstraint("CHK_POB_NOT_EMPTY", "LEN(LTRIM(RTRIM([PlaceOfBirth]))) > 0");
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.People.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasFilter("[Name] <> ''");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers", null, t =>
                        {
                            t.HasCheckConstraint("CHK_TEACHER_NAME_NOT_EMPTY", "LEN(LTRIM(RTRIM([Name]))) > 0");
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.People.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SchoolAPI.Models.Registrations.Registration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrolledBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("EnrolledBy");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("RejectedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("SchoolAPI.Models.Schedules.Schedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules", null, t =>
                        {
                            t.HasCheckConstraint("CHK_DAYOFWEEK_NOT_EMPTY", "LEN(LTRIM(RTRIM([Day]))) > 0");

                            t.HasCheckConstraint("CHK_STARTTIME_BEFORE_ENDTIME", "[StartTime] < [EndTime]");
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.School_Structure.Class", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] <> ''");

                    b.ToTable("Classes", null, t =>
                        {
                            t.HasCheckConstraint("CHK_CAPACITY_NOT_EMPTY", "[Capacity] > 0");

                            t.HasCheckConstraint("CHK_CLASS_NAME_NOT_EMPTY", "LEN(LTRIM(RTRIM([Name]))) > 0");
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.School_Structure.Level", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SchoolLevelId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] <> ''");

                    b.HasIndex("SchoolLevelId");

                    b.ToTable("Levels", null, t =>
                        {
                            t.HasCheckConstraint("CHK_LEVEL_NAME_NOT_EMPTY", "LEN(LTRIM(RTRIM([Name]))) > 0");
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.School_Structure.SchoolLevel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] <> ''");

                    b.ToTable("SchoolLevels", null, t =>
                        {
                            t.HasCheckConstraint("CHK_SCHOOLLEVEL_NAME_NOT_EMPTY", "LEN(LTRIM(RTRIM([Name]))) > 0");
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.Curriculum_Bridges.ClassSubject", b =>
                {
                    b.HasOne("SchoolAPI.Models.School_Structure.Class", "Class")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.Curriculum_Bridges.Subject", "Subject")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolAPI.Models.Curriculum_Bridges.TeacherSubjectClass", b =>
                {
                    b.HasOne("SchoolAPI.Models.School_Structure.Class", "Class")
                        .WithMany("TeacherSubjectClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.Curriculum_Bridges.Subject", "Subject")
                        .WithMany("TeacherSubjectClasses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.People.Teacher", "Teacher")
                        .WithMany("TeacherSubjectClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolAPI.Models.Enrollment.Enrollment", b =>
                {
                    b.HasOne("SchoolAPI.Models.School_Structure.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.Registrations.Registration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.People.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Registration");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolAPI.Models.PaymentsWaitlists.Payment", b =>
                {
                    b.HasOne("SchoolAPI.Models.People.User", "ReceivedUser")
                        .WithMany("ReceivedPayments")
                        .HasForeignKey("ReceivedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.People.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.People.User", "VerifiedUser")
                        .WithMany("VerifiedPayments")
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReceivedUser");

                    b.Navigation("Student");

                    b.Navigation("VerifiedUser");
                });

            modelBuilder.Entity("SchoolAPI.Models.PaymentsWaitlists.Waitlist", b =>
                {
                    b.HasOne("SchoolAPI.Models.School_Structure.Class", "Class")
                        .WithMany("Waitlists")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.People.Student", "Student")
                        .WithMany("Waitlists")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolAPI.Models.People.Student", b =>
                {
                    b.HasOne("SchoolAPI.Models.School_Structure.Class", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassId");

                    b.HasOne("SchoolAPI.Models.School_Structure.Level", null)
                        .WithMany("Students")
                        .HasForeignKey("LevelId");

                    b.HasOne("SchoolAPI.Models.People.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("SchoolAPI.Models.People.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolAPI.Models.People.Teacher", b =>
                {
                    b.HasOne("SchoolAPI.Models.People.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("SchoolAPI.Models.People.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolAPI.Models.Registrations.Registration", b =>
                {
                    b.HasOne("SchoolAPI.Models.School_Structure.Class", "Class")
                        .WithMany("Registrations")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.People.User", "EnrolledUser")
                        .WithMany()
                        .HasForeignKey("EnrolledBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolAPI.Models.People.User", "ProcessedUser")
                        .WithMany("ProcessedRegistrations")
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolAPI.Models.People.User", "RejectedUser")
                        .WithMany()
                        .HasForeignKey("RejectedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolAPI.Models.People.Student", "Student")
                        .WithMany("Registrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("EnrolledUser");

                    b.Navigation("ProcessedUser");

                    b.Navigation("RejectedUser");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolAPI.Models.Schedules.Schedule", b =>
                {
                    b.HasOne("SchoolAPI.Models.School_Structure.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.Curriculum_Bridges.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.People.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolAPI.Models.School_Structure.Class", b =>
                {
                    b.HasOne("SchoolAPI.Models.School_Structure.Level", "Level")
                        .WithMany("Classes")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("SchoolAPI.Models.School_Structure.Level", b =>
                {
                    b.HasOne("SchoolAPI.Models.School_Structure.SchoolLevel", "SchoolLevel")
                        .WithMany("Levels")
                        .HasForeignKey("SchoolLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SchoolLevel");
                });

            modelBuilder.Entity("SchoolAPI.Models.Curriculum_Bridges.Subject", b =>
                {
                    b.Navigation("ClassSubjects");

                    b.Navigation("Schedules");

                    b.Navigation("TeacherSubjectClasses");
                });

            modelBuilder.Entity("SchoolAPI.Models.People.Student", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Registrations");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("SchoolAPI.Models.People.Teacher", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("TeacherSubjectClasses");
                });

            modelBuilder.Entity("SchoolAPI.Models.People.User", b =>
                {
                    b.Navigation("ProcessedRegistrations");

                    b.Navigation("ReceivedPayments");

                    b.Navigation("Student");

                    b.Navigation("Teacher");

                    b.Navigation("VerifiedPayments");
                });

            modelBuilder.Entity("SchoolAPI.Models.School_Structure.Class", b =>
                {
                    b.Navigation("ClassSubjects");

                    b.Navigation("Registrations");

                    b.Navigation("Schedules");

                    b.Navigation("Students");

                    b.Navigation("TeacherSubjectClasses");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("SchoolAPI.Models.School_Structure.Level", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolAPI.Models.School_Structure.SchoolLevel", b =>
                {
                    b.Navigation("Levels");
                });
#pragma warning restore 612, 618
        }
    }
}
