using Mapster;
using SchoolAPI.DTOs.Schedule;
using SchoolAPI.Models.Schedules;

namespace SchoolAPI.Mappings
{
    public class ScheduleProfile : IRegister
    {
        public void Register(TypeAdapterConfig config)
        {
            config.NewConfig<Schedule, ScheduleResponseDto>()
            .Map(dest => dest.Day, src => src.Day.ToString())
            .Map(dest => dest.StartTime, src => src.StartTime.ToString(@"hh\:mm"))
            .Map(dest => dest.EndTime, src => src.EndTime.ToString(@"hh\:mm"))
            .Map(dest => dest.IsFreePeriod, src => src.SubjectId == null)
            .Map(dest => dest.Class, src => new ClassSummaryDto(src.Class.Id, src.Class.Name))
            .Map(dest => dest.Subject, src => src.Subject == null ? null
                : new SubjectSummaryDto(src.Subject.Id, src.Subject.Name, src.Subject.Code))
            .Map(dest => dest.Teacher, src => src.Teacher == null ? null
                : new TeacherSummaryDto(src.Teacher.Id, src.Teacher.Name, src.Teacher.Specialization));

            config.NewConfig<ScheduleRequestCreateDto, Schedule>()
                .Ignore(dest => dest.Id)
                .Ignore(dest => dest.CreatedAt)
                .Ignore(dest => dest.UpdatedAt!)
                .Ignore(dest => dest.IsAutoGenerated)
                .Ignore(dest => dest.Class)
                .Ignore(dest => dest.Subject)
                .Ignore(dest => dest.Teacher);
        }
    }
}
