using SchoolAPI.Models.SubjectAndBridge;
using SchoolAPI.Models.People;
using SchoolAPI.Models.School_Structure;

namespace SchoolAPI.Models.Schedules
{
    public class Schedule
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();

        public SchoolDay Day { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }

        public bool IsFreePeriod { get; set; }
        public bool IsAutoGenerated { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public string ClassId { get; set; } = default!;
        public Class Class { get; set; } = default!;

        public string? SubjectId { get; set; }
        public Subject Subject { get; set; } = default!;

        public string? TeacherId { get; set; }
        public Teacher Teacher { get; set; } = default!;
    }
}
