using SchoolAPI.Models.Curriculum_Bridges;
using SchoolAPI.Models.People;
using SchoolAPI.Models.School_Structure;

namespace SchoolAPI.Models.Schedules
{
    public class Schedule
    {
        public string Id { get; set; }

        public SchoolDay Day { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }

        public bool IsAutoGenerated { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public string ClassId { get; set; } = default!;
        public Class Class { get; set; } = default!;

        public string SubjectId { get; set; } = default!;
        public Subject Subject { get; set; } = default!;

        public string TeacherId { get; set; } = default!;
        public Teacher Teacher { get; set; } = default!;
    }
}
