using SchoolAPI.Models.Schedules;

namespace SchoolAPI.DTOs.Schedule;

// Response DTOs
public record ScheduleResponseDto(
    string Id,
    string Day,
    string StartTime,
    string EndTime,
    bool IsAutoGenerated,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    ClassSummaryDto Class,
    SubjectSummaryDto Subject,
    TeacherSummaryDto Teacher
);

public record ClassSummaryDto(string Id, string Name);
public record SubjectSummaryDto(string Id, string Name, string Code);
public record TeacherSummaryDto(string Id, string Name, string Specialization);

// Request DTOs
public record ScheduleRequestCreateDto(
    string ClassId,
    string SubjectId,
    string TeacherId,
    SchoolDay Day,
    TimeSpan StartTime,
    TimeSpan EndTime
);

public record ScheduleRequestUpdateDto(
    string TeacherId,
    SchoolDay Day,
    TimeSpan StartTime,
    TimeSpan EndTime
);

// Auto-generation DTO
public record AutoGenerateScheduleRequestDto(
    string ClassId,
    TimeSpan DayStartTime,       // e.g. 07:00
    TimeSpan DayEndTime,         // e.g. 17:00
    int PeriodDurationMinutes,   // e.g. 60
    int BreakDurationMinutes     // e.g. 15
);
