using SchoolAPI.Models.Schedules;

namespace SchoolAPI.DTOs.Schedule;

// Response DTOs
public record ScheduleResponseDto(
    string Id,
    SchoolDay Day,
    TimeSpan StartTime,
    TimeSpan EndTime,
    bool IsAutoGenerated,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    ClassSummaryDto Class,
    SubjectSummaryDto Subject,
    TeacherSummaryDto Teacher
);

public record ClassSummaryDto(string Id, string Name);
public record SubjectSummaryDto(string Id, string Name, string Code);
public record TeacherSummaryDto(string Id, string Name, string Specialization);
